var KeyConstant = {
    'cid': 'Category',
    'name': 'CategoryName',
    'description': 'Description',
    'metaTitle': 'MetaTitle',
    'metaDescription': 'MetaDescription',
    'metaKeywords': 'MetaKeywords',
    'ogTitle': 'OGTitle',
    'ogDescription': 'OGDescription',
    'alias': 'SeoUrl',
    'userName': 'UserName',
    'phone': 'Phone',
    'country': 'Country',
    'sex': 'Sex',
    'about': 'About',
    'profileTitle': 'ProfileTitle',
    'address': 'Address',
    'dob': 'DOB',
    'accountHolderName': 'AccountHolderName',
    'accountNumber': 'AccountNumber',
    'ifscCode': 'IFSCCode',
    'bankName': 'BankName',
    'bankAddress': 'BranchName',
    'paytmNumber': 'PaytmNumber',
    'preferredPaymentMode': 'PreferredMode',
    'reason': 'RejectReason'
};